services:
  postgres:
    image: postgres:16-alpine
    container_name: inventaire-postgres
    environment:
      POSTGRES_DB: inventaire_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - inventaire_pgdata:/var/lib/postgresql/data

volumes:
  inventaire_pgdata:
